# main.yml
---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: true

  vars_files:
   - vars/main.yml

  roles:
   - { role: preparations, when: ansible_os_family == "Debian"}
   - jenkins
   - {role: iptables, when: ansible_os_family == "Debian"}
   - {role: finalization, when: ansible_os_family == "Debian"}
