---
- name: users | Generating Jenkins SSH Keys
  user:
    name: "jenkins"
    generate_ssh_key: yes

- name: users | Adding Jenkins Account To Sudoers
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^jenkins ALL"
    line: "jenkins ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
    state: "present"
  when: >
        enable_jenkins_sudo is defined and
        enable_jenkins_sudo
